In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import LinearSVR, SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor


import warnings
warnings.filterwarnings(action='ignore')

In [2]:
df1 = pd.read_csv('/Users/shubhvashishth/Downloads/MagicBricks.csv')
df1

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0
...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,55000000,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,12500000,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,17500000,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,11500000,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,18500000,Ready_to_move,New_Property,Builder_Floor,12916.0

In [3]:
df1.isna().sum()

Area             0
BHK              0
Bathroom         2
Furnishing       5
Locality         0
Parking         33
Price            0
Status           0
Transaction      0
Type             5
Per_Sqft       241
dtype: int64

In [4]:
dummies_1 = pd.get_dummies(df1.Furnishing)
dummies_1.head()

   Furnished  Semi-Furnished  Unfurnished
0          0               1            0
1          0               1            0
2          1               0            0
3          0               1            0
4          0               1            0

In [5]:
df2 = pd.concat([df1,dummies_1],axis='columns')
df2

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft,Furnished,Semi-Furnished,Unfurnished
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN,0,1,0
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0,0,1,0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0,1,0,0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0,0,1,0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,55000000,Ready_to_move,New_Property,Builder_Floor,12916.0,0,0,1
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,12500000,Ready_to_move,Resale,Builder_Floor,12916.0,0,1,0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,17500000,Ready_to_move,New_Property,Builder_Floor,12916.0,0,1,0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,11500000,Ready_to_move,Resale,Builder_Floor,12916.0,0,0,1
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,18500000,Ready_to_move,New_Property,Builder_Floor,12916.0,0,0,1

In [6]:
df3 = df2.drop(['Status','Per_Sqft','Furnishing'],axis='columns')
df3.head()

,Area,BHK,Bathroom,Locality,Parking,Price,Transaction,Type,Furnished,Semi-Furnished,Unfurnished
0,800.0,3,2.0,Rohini Sector 25,1.0,6500000,New_Property,Builder_Floor,0,1,0
1,750.0,2,2.0,"J R Designers Floors, Rohini Sector 24",1.0,5000000,New_Property,Apartment,0,1,0
2,950.0,2,2.0,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Resale,Apartment,1,0,0
3,600.0,2,2.0,Rohini Sector 24,1.0,4200000,Resale,Builder_Floor,0,1,0
4,650.0,2,2.0,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,New_Property,Builder_Floor,0,1,0

In [7]:
dummies2 = pd.get_dummies(df3.Transaction)
dummies2.head()

   New_Property  Resale
0             1       0
1             1       0
2             0       1
3             0       1
4             1       0

In [8]:
dummies3 = pd.get_dummies(df3.Type)
dummies3.head()

   Apartment  Builder_Floor
0          0              1
1          1              0
2          1              0
3          0              1
4          0              1

In [9]:
df4 = pd.concat([df3,dummies2,dummies3],axis='columns')
df4.head()

,Area,BHK,Bathroom,Locality,Parking,Price,Transaction,Type,Furnished,Semi-Furnished,Unfurnished,New_Property,Resale,Apartment,Builder_Floor
0,800.0,3,2.0,Rohini Sector 25,1.0,6500000,New_Property,Builder_Floor,0,1,0,1,0,0,1
1,750.0,2,2.0,"J R Designers Floors, Rohini Sector 24",1.0,5000000,New_Property,Apartment,0,1,0,1,0,1,0
2,950.0,2,2.0,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Resale,Apartment,1,0,0,0,1,1,0
3,600.0,2,2.0,Rohini Sector 24,1.0,4200000,Resale,Builder_Floor,0,1,0,0,1,0,1
4,650.0,2,2.0,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,New_Property,Builder_Floor,0,1,0,1,0,0,1

In [10]:
df5 = df4.drop(['Transaction','Type'],axis='columns')
df5.head()

,Area,BHK,Bathroom,Locality,Parking,Price,Furnished,Semi-Furnished,Unfurnished,New_Property,Resale,Apartment,Builder_Floor
0,800.0,3,2.0,Rohini Sector 25,1.0,6500000,0,1,0,1,0,0,1
1,750.0,2,2.0,"J R Designers Floors, Rohini Sector 24",1.0,5000000,0,1,0,1,0,1,0
2,950.0,2,2.0,"Citizen Apartment, Rohini Sector 13",1.0,15500000,1,0,0,0,1,1,0
3,600.0,2,2.0,Rohini Sector 24,1.0,4200000,0,1,0,0,1,0,1
4,650.0,2,2.0,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,0,1,0,1,0,0,1

In [11]:
df5.isna().sum()

Area               0
BHK                0
Bathroom           2
Locality           0
Parking           33
Price              0
Furnished          0
Semi-Furnished     0
Unfurnished        0
New_Property       0
Resale             0
Apartment          0
Builder_Floor      0
dtype: int64

In [12]:
df5.Bathroom.unique()

array([ 2.,  3.,  4.,  1., nan,  5.,  6.,  7.])

In [13]:
df5[df5.Bathroom>df5.BHK+1]

,Area,BHK,Bathroom,Locality,Parking,Price,Furnished,Semi-Furnished,Unfurnished,New_Property,Resale,Apartment,Builder_Floor
248,10350.0,4,7.0,"Maharani Bagh, New Friends Colony",3.0,160000000,0,1,0,1,0,1,0
1029,5236.0,5,7.0,"The Amaryllis, Karol Bagh",3.0,73700000,0,0,1,1,0,1,0
1081,1250.0,2,4.0,Sheikh Sarai,1.0,19000000,0,1,0,0,1,0,1
1211,4350.0,4,6.0,"Orchid Metropolis, Hauz Khas",2.0,135000000,0,1,0,1,0,1,0

In [14]:
df6 = df5[df5.Bathroom<df5.BHK+2]
df6

,Area,BHK,Bathroom,Locality,Parking,Price,Furnished,Semi-Furnished,Unfurnished,New_Property,Resale,Apartment,Builder_Floor
0,800.0,3,2.0,Rohini Sector 25,1.0,6500000,0,1,0,1,0,0,1
1,750.0,2,2.0,"J R Designers Floors, Rohini Sector 24",1.0,5000000,0,1,0,1,0,1,0
2,950.0,2,2.0,"Citizen Apartment, Rohini Sector 13",1.0,15500000,1,0,0,0,1,1,0
3,600.0,2,2.0,Rohini Sector 24,1.0,4200000,0,1,0,0,1,0,1
4,650.0,2,2.0,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Chittaranjan Park,3.0,55000000,0,0,1,1,0,0,1
1255,1050.0,3,2.0,Chittaranjan Park,3.0,12500000,0,1,0,0,1,0,1
1256,875.0,3,3.0,Chittaranjan Park,3.0,17500000,0,1,0,1,0,0,1
1257,990.0,2,2.0,Chittaranjan Park Block A,1.0,11500000,0,0,1,0,1,0,1
1258,11050.0,3,3.0,Chittaranjan Park,1.0,18500000,0,0,1,1,0,0,1

In [15]:
df6.Parking.unique()

array([  1.,   5.,   2.,   4.,  nan,   9.,   3.,  39.,  10., 114.])

In [16]:
df7 = df6[df6.Parking<10]
df7.head()

,Area,BHK,Bathroom,Locality,Parking,Price,Furnished,Semi-Furnished,Unfurnished,New_Property,Resale,Apartment,Builder_Floor
0,800.0,3,2.0,Rohini Sector 25,1.0,6500000,0,1,0,1,0,0,1
1,750.0,2,2.0,"J R Designers Floors, Rohini Sector 24",1.0,5000000,0,1,0,1,0,1,0
2,950.0,2,2.0,"Citizen Apartment, Rohini Sector 13",1.0,15500000,1,0,0,0,1,1,0
3,600.0,2,2.0,Rohini Sector 24,1.0,4200000,0,1,0,0,1,0,1
4,650.0,2,2.0,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,0,1,0,1,0,0,1

In [17]:
df7.isna().sum()

Area              0
BHK               0
Bathroom          0
Locality          0
Parking           0
Price             0
Furnished         0
Semi-Furnished    0
Unfurnished       0
New_Property      0
Resale            0
Apartment         0
Builder_Floor     0
dtype: int64

In [18]:
df7.Area.describe()

count     1211.000000
mean      1469.183807
std       1564.350249
min         28.000000
25%        810.000000
50%       1200.000000
75%       1700.000000
max      24300.000000
Name: Area, dtype: float64

In [19]:
df8 = df7[df7.Area>100]
df8

,Area,BHK,Bathroom,Locality,Parking,Price,Furnished,Semi-Furnished,Unfurnished,New_Property,Resale,Apartment,Builder_Floor
0,800.0,3,2.0,Rohini Sector 25,1.0,6500000,0,1,0,1,0,0,1
1,750.0,2,2.0,"J R Designers Floors, Rohini Sector 24",1.0,5000000,0,1,0,1,0,1,0
2,950.0,2,2.0,"Citizen Apartment, Rohini Sector 13",1.0,15500000,1,0,0,0,1,1,0
3,600.0,2,2.0,Rohini Sector 24,1.0,4200000,0,1,0,0,1,0,1
4,650.0,2,2.0,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Chittaranjan Park,3.0,55000000,0,0,1,1,0,0,1
1255,1050.0,3,2.0,Chittaranjan Park,3.0,12500000,0,1,0,0,1,0,1
1256,875.0,3,3.0,Chittaranjan Park,3.0,17500000,0,1,0,1,0,0,1
1257,990.0,2,2.0,Chittaranjan Park Block A,1.0,11500000,0,0,1,0,1,0,1
1258,11050.0,3,3.0,Chittaranjan Park,1.0,18500000,0,0,1,1,0,0,1

In [20]:
df8.Area.describe()

count     1194.000000
mean      1489.178048
std       1566.382668
min        125.000000
25%        820.000000
50%       1200.000000
75%       1700.000000
max      24300.000000
Name: Area, dtype: float64

In [21]:
df8.Locality.unique()

array(['Rohini Sector 25', 'J R Designers Floors, Rohini Sector 24',
       'Citizen Apartment, Rohini Sector 13', 'Rohini Sector 24',
       'Rohini Sector 24 carpet area 650 sqft status Ready to Move floor 4 out of 4 floors transaction New Property furnishing Semi-Furnished facing East overlooking Garden/Park, Main Road car parking 1 Open bathroom 2 balcony 1 ownership Freehold Newly Constructed Property Newly Constructed Property East Facing Property 2BHK Newly build property for Sale. A House is waiting for a Friendly Family to make it a lovely home.So please come and make his house feel alive once again. read more Contact Agent View Phone No. Share Feedback Garima properties Certified Agent Trusted by Users Genuine Listings Market Knowledge',
       'Delhi Homes, Rohini Sector 24', 'Rohini Sector 21',
       'Rohini Sector 22', 'Rohini Sector 20',
       'Rohini Sector 8 How Auctions work? The borrower has the physical possession of the Property. However the lender (Bank) can legally sell the Property. super area 32 sqm status Ready to Move floor 1 transaction Resale furnishing Semi-Furnished Contact Now Enquire Now Auction By',
       'Rohini Sector 25 carpet area 660 sqft status Ready to Move floor 2 out of 4 floors transaction New Property furnishing Semi-Furnished facing North overlooking Garden/Park, Main Road car parking 1 Open bathroom 2 balcony 1 ownership Freehold Newly Constructed Property Newly Constructed Property Near by Ryan international school 2BHK Located on the Ground Floor of a four story building with open parking the flat measure 720 Sq Ft the property is located in a green and plush sector with common parks opposite every lane and bus and auto stand nearby. its situated 1.5 km from the metro station and walkable distance from shopping distance from shopping complex. read more Contact Agent View Phone No. Share Feedback Know your Certified Agent CRISIL Rating No of Employees 9 Kulwant & Company Certified Agent Trusted by Users Genuine Listings 5500+ Buyers Served',
       'Rohini Sector 16', 'Rohini Sector 14',
       'Mayur Apartment, Rohini Sector 9', 'Vijay Vihar, Rohini',
       'Rohini Sector 18 carpet area 40 sqm status Ready to Move floor 2 out of 4 floors transaction Resale furnishing Furnished facing East overlooking Main Road car parking 2 Open bathroom 1 balcony 1 ownership Freehold East Facing Property It an LIG three side corner flat in second floor, having full scope of expansion. interior decorated with 2 textured wall , kajaria tiles , fully modular kitchen, branded bathroom and toilet fittings, LED panel, ac in one bedroom, false ceiling in entire flat.south facing unobstructed view balcony. It was all renovated only 2.5 yrs back so every thing is in brand new condition. read more Contact Owner View Phone No. Share Feedback Owner Pramod',
       'Prashant Vihar, Rohini', 'Rohini Sector 5',
       'Sanskriti Apartment, Rohini Sector 28', 'Rohini Sector 19',
       'Lajpat Nagar 1', 'Lajpat Nagar', 'Vikram Vihar, Lajpat Nagar',
       'Lajpat Nagar 4', 'Lajpat Nagar 3',
       'Dayanand Colony, Lajpat Nagar How Auctions work? The borrower has the physical possession of the Property. However the lender (Bank) can legally sell the Property. super area 810 sqft status Ready to Move floor 1 out of 5 floors transaction Resale balcony 1 Contact Now Enquire Now Auction By Bank',
       'Lajpat Nagar 2', 'Amar Colony, Lajpat Nagar',
       'DDA Flats Sector 14, Dwarka Sector 14',
       'Siddhartha Heights, Dwarka Sector 24',
       'MTNL Employees House Welfare Society, Dwarka Sector 24',
       'Delhi Homes Yojana, Dwarka Sector 24',
       'The Elite Spire, Dwarka Sector 21',
       'Kunj Vihar Apartment, Dwarka Sector 12',
       'Ashirwad Apartments, Dwarka Sector 12',
       'Sunny Valley Apartments, Dwarka',
       'Shri Agrasen Apartment, Dwarka Sector 7',
       'Chopra Apartment, Dwarka Sector 23',
       'Mohinder Apartments, Dwarka Sector 12',
       'Chander Lok Apartment, Dwarka Sector 19',
       'Neelachal, Dwarka Sector 5', 'Dwarka',
       'MeeraBai Apartment, Dwarka Sector 5',
       'Crescent Apartments, Dwarka Sector 18',
       'Ashoka Enclave Apartment, Dwarka Sector 11',
       'Nav Kairali Apartment, Dwarka Sector 3',
       'Ashirwad Apartments, Dwarka',
       'Indraprastha Apartment, Dwarka Sector 12',
       'Mohinder Apartments, Dwarka',
       'Ashoka Apartments, Dwarka Sector 12',
       'Karuna Vihar Apartment, Dwarka', 'LNT Apartments, Dwarka',
       'Dwarka Sector 4',
       'Dwarka Sector 3 carpet area 400 sqft status Ready to Move floor 1 out of 4 floors transaction New Property furnishing Semi-Furnished facing West overlooking Main Road bathroom 1 balcony 1 ownership Freehold Newly Constructed Property 1BHK freehold property , reserved parking, ample space for visitor parking, bathrooms with modern facilities, complete light in all room, wooden wardrobes in bedrooms, separate electric & water meter connection, separate water tank at roof, electronic door lock system with intercom facility, wall to wall POP work, fall ceiling work in all rooms, royal paint work in all rooms, 24X7 running water, branded electric fittings, modular kitchen with electronic chimney, marble vitrified tile flooring, near to metro station, well connected to main road ect. 80 to 90 home loan available. Ready to move read more Contact Agent View Phone No. Share Feedback Agent S.B. Associates 4000+ Buyers Served',
       'Dwarka Sector 16B', 'Vinoba Puri, Lajpat Nagar', 'Budh Vihar',
       'Budh Vihar super area 50 sqyrd status Ready to Move floor Ground out of 2 floors transaction Resale furnishing Unfurnished facing East car parking 1 Open bathroom 1 balcony 2 ownership Freehold For Sale 2 BHK 50 yrd, 2 side open Ground Floor, First and Second Floor in H Block, Gali No. 04, Near Laxmi Narain Mandir, BudhVihar read more Contact Agent View Phone No. Share Feedback Agent Sahyog Properties 1000+ Buyers Served',
       'Budh Vihar Phase 1', 'Budh Vihar Phase 2',
       'Saptrishi Apartment, Rohini Sector 23', 'Rohini Sector 23',
       'Rohini ( 1 km from Shahbad Dairy, Rohini)',
       'The Leela Sky Villas, Patel Nagar',
       'Uttam Nagar Floors, Uttam Nagar', 'Virat Residency, Dwarka Mor',
       'Find Homes, Greater Kailash 2', 'Adarsh Homes, Dwarka Mor',
       'Kushwaha Homes, Uttam Nagar', 'Godrej South Estate, Okhla',
       'APL Builder Floor, Greater Kailash 1', 'Janakpuri Block A3',
       'Greater Kailash 2', 'Partap Homes, Bhagwati Vihar, Uttam Nagar',
       'The Amaryllis, Karol Bagh',
       'Diamond Heights Multi Estate, Najafgarh',
       'Vasant Vihar Builder Floor, Vasant Vihar', 'Vasant Kunj',
       'Greater Kailash 1', 'Khanpur, Madangir',
       'Friends Colony West, New Friends Colony', 'New Friends Colony',
       'Maharani Bagh, New Friends Colony',
       'New Friends Colony carpet area 4300 sqft status Ready to Move floor 2 out of 3 floors transaction Resale furnishing Unfurnished facing North - East overlooking Garden/Park, Main Road car parking 2 Covered, 2 Open bathroom 4 balcony 3 ownership Freehold hurry up... dont waste time any where, It is best deal in your pocket budget.well maintained second floor with terrace garden plus 2 additional room on terrace up for sale in new friends colony.the property has 4 king sized bedroom attached bathroom with roof top shower with Jacuzzi. It has 3 big balconies with wonderful outer view. It has modular kitchen with new fittings. It has servant quarter pooja room study room store room etc. It has drawing & dining. It has 2 car parking with gated society. It has 247 hours water supply with full power backup. It is in amazing location. read more Contact Agent View Phone No. Share Feedback Crisil Silver Agent Sagar Home Developers Pvt. Ltd. 1000+ Buyers Served',
       'Friends Colony East, New Friends Colony',
       'Kalindi Colony, Maharani Bagh, New Friends Colony',
       'Taimoor Enclave, New Friends Colony carpet area 2800 sqft status Ready to Move floor 2 out of 3 floors transaction Resale furnishing Semi-Furnished facing East overlooking Garden/Park society Taimoor Enclave car parking 2 Covered, 1 Open bathroom 4 balcony 2 ownership Freehold Two floor of the house is available for sale SECOND AND THIRD FLOOR EXTRA made, provision for LIFT can be provided by the OWNER .DDA FLATS of TAIMOOR ENCLAVE, NEAR GURUDWARA, NEW FRIENDS COLONY, SOUTH DELHI , HOUSE IS ON THE SECOND FLOOR have 3 bed room and 2 wash room and and same on the Third Floor, URGENT SALE, BROKER EXCUSE. read more Contact Agent View Phone No. Share Feedback Agent Delhi Homes 100+ Buyers Served',
       'New Friends Colony Floors, New Friends Colony',
       'Kailash Colony, Greater Kailash',
       'Hans Apartments, Vishwas Nagar, Shahdara',
       'Naveen Shahdara, Shahdara', 'Balbir Nagar, Shahdara',
       'Rohitash Nagar East, Shahdara', 'Shahdara',
       'Vishwas Nagar, Shahdara',
       'DDA RPS Flats, Mansarowar Park, Shahdara',
       'Yamuna Vihar, Shahdara', 'Ram Nagar, Shahdara',
       'Rohtash Nagar, Shahdara', 'Ram Nagar Extension, Shahdara',
       'Maujpur, Shahdara', 'Mansarowar Park, Shahdara',
       'Gorakh Park West, Shahdara', 'Shivnam Apartment, Shahdara',
       'Jyoti Colony, Shahdara', 'Ahinsha Vatika, Ram Nagar, Shahdara',
       'mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar',
       'Laxmi Nagar', 'Guru Angad Nagar West, Laxmi Nagar',
       'Lalita Park, Laxmi Nagar', 'Krishan Kunj, Laxmi Nagar',
       'Laxmi Nagar super area 450 sqft status Ready to Move floor 3 out of 4 floors transaction New Property furnishing Semi-Furnished facing East overlooking Main Road bathroom 2 balcony 1 ownership Freehold Newly Constructed Property East Facing Property This Builder Floor Apartment at 3rd faces East & overlooks Main Road offering a beautiful view from the house. with airy interiors. The type of ownership is Freehold. The Builder Floor Apartment is newly constructed. Bank loans available from LIC Housing Finance, Kotak Mahindra Bank, Indiabulls. Flooring of type Marble covers maximum part of the house. The location has easy access to, Dena Bank (0 km ), Delhi Convent School (0 km ), DDA Market (0 km ) and Nirman Vihar Metro Station (2 km ). read more Contact Owner View Phone No. Share Feedback Owner Sonia',
       "Laxmi Nagar carpet area 1000 sqft status Ready to Move floor 1 out of 4 floors transaction Resale furnishing Furnished bathroom 3 balcony 1 It's a 1st floor Builder Floor Apartment in a building of total 4 floors. The age of construction for this Builder Floor Apartment is between 10 to 15 years. The location has easy access to, Dena Bank (0 km ), Delhi Convent School (0 km ), DDA Market (0 km ) and Nirman Vihar Metro Station (2 km ). read more Contact Owner View Phone No. Share Feedback Owner Vipul Jain",
       'Bank Enclave, Laxmi Nagar', 'Uttam Nagar', 'Dwarka Mor',
       'Uttam Nagar West', 'SB Residency, Dwarka Mor',
       'Kiran Garden, Uttam Nagar', 'Mohan Garden, Razapur Khurd',
       'Mitya Homes, Dwarka Mor',
       'Uttam Nagar carpet area 550 sqft status Ready to Move transaction New Property furnishing Semi-Furnished facing East overlooking Main Road bathroom 2 balcony 1 ownership Freehold Newly Constructed Property Newly Constructed Property East Facing Property 2bhk fully furnished flats available for sale at uttam nagar, the flat is fully loaded, one singal wall texture in all bedrooms, modular kitchen, LED pannel in drawing room, wardrobes in bedroom read more Contact Agent View Phone No. Share Feedback Pranita Developers Pvt. Ltd. Certified Agent Trusted by Users Genuine Listings 100+ Buyers Served',
       'New Uttam Nagar, Uttam Nagar', 'Patel Nagar West',
       'Patel Nagar East, Patel Nagar', 'Punjabi Basti, Patel Nagar',
       'Baljit Nagar, Patel Nagar',
       'DDA Flats Vasant Kunj, Vasant Kunj Sector B',
       'DDA Flats Vasant Kunj, Vasant Kunj carpet area 1200 sqft status Ready to Move floor 5 out of 7 floors transaction Resale furnishing Semi-Furnished facing North - West overlooking Garden/Park, Main Road society DDA Flats Vasant Kunj car parking 1 Covered, 1 Open bathroom 2 balcony 2 ownership Freehold A southEAST facing 3 bhk resale flat is available in the promising locality of sectorE vasant kunj vasant kunj, delhi south. It is a ready to move in spacious flat and is located on the 5th floor. Every single detail of the flat is carefully designed. This property offers quality specifications such as lifts, park, water storage and securityfire alar. It is a gated society flat. It provides a spectacular view of the main road and parkgarden. The apartment is priced at rs. 2 cr. It is a freehold property, with a super builtUp area of 1600 sq. Ft. The property price is negotiable. read more Contact Agent Enquire Now Share Feedback Crisil Silver Agent Link Properties Pvt. Ltd. 5000+ Buyers Served',
       'DDA Flats Vasant Kunj, Vasant Kunj',
       'DDA Flats Pocket 1, Vasant Kunj Sector B',
       'Saraswati Narmada Ganga Yamuna Apartment, Vasant Kunj Sector D',
       'DDA Flats Sector E Pocket 1, Vasant Kunj',
       'DDA Flats Vasant Kunj, Vasant Kunj Sector D',
       'Vasant Kunj Sector A', 'E2 Vasant Kunj, Vasant Kunj',
       'Ganga Apartment Sector D Pocket 6, Vasant Kunj',
       'Vasant Kunj Sector C', 'Vasant Kunj Sector D',
       'DDA Flats Vasant Kunj, Vasant Kunj Sector C',
       'Kishangarh, Vasant Kunj', 'DDA Pocket 1, Vasant Kunj Sector D',
       'Vasant Kunj Sector B', 'Sukhdev Vihar, Okhla', 'Geeta Colony',
       'Krishna Nagar Block A', 'Taj Enclave, Khairatabad',
       'Shastri Park, Shahdara', 'Sitaram Bazar, Chandni Chowk',
       'Shahdara How Auctions work? The borrower has the physical possession of the Property. However the lender (Bank) can legally sell the Property. super area 852 sqft status Ready to Move transaction Resale ownership Freehold bathroom 2 Contact Now Enquire Now Auction By',
       'Saket', 'Anupam Enclave, Saket', 'RWA Flats, Saket',
       'Metrotech Builder Floors, Saket',
       'Saket Court Residential Complex, Saket',
       'Press Enclave Society, Saket',
       'Project Paryavaran Complex, Saket',
       'Arjun Nagar, Safdarjung Enclave', 'Safdarjung Enclave',
       "Safdarjung Enclave carpet area 1100 sqft status Ready to Move floor Ground out of 4 floors transaction Resale furnishing Unfurnished facing North - East overlooking Garden/Park, Main Road car parking 1 Covered, 1 Open bathroom 3 balcony 3 ownership Freehold if you are searching for your dream house, congratulation. you're not so far from your destiny. we got unbeatable ground floor in b-block safdarjung enclave for sale. it is in 150 yds. It has 3 large king sized bedroom attached bathroom with Jacuzzi and roof top shower with all other fittings. it has modular kitchen with all needed facility. it has 3 big balcony with amazing out side view. it has 1 servant quarter also. it has 1 reserved car parking with gated society. It has 24*7 water supply with full power backup. for more information contact us at once because it can be your dream house. read more Contact Agent View Phone No. Share Feedback Crisil Silver Agent Sagar Home Developers Pvt. Ltd. 1000+ Buyers Served",
       'Krishna Nagar-Safdarjung Enclave',
       'Safdarjung Enclave carpet area 3250 sqft status Ready to Move floor 1 out of 4 floors transaction Resale furnishing Semi-Furnished facing North - East overlooking Garden/Park, Main Road car parking 1 Covered bathroom 4 balcony 3 ownership Freehold Near Buy Green park Metro station. The location of the property is Awesome and Peaceful. The construction is very Highend and Very tasteful Done-up. The Same property is location on the FF. 4 Side corner read more Contact Agent Enquire Now Share Feedback Crisil Silver Agent Findahouse Real Estate Consultants LLP 2000+ Buyers Served',
       'Safdarjung Enclave carpet area 290 sqyrd status Ready to Move floor 2 out of 3 floors transaction Resale furnishing Semi-Furnished facing West overlooking Main Road car parking 2 Open bathroom 4 balcony 3 ownership Freehold Opposite Deer Park.The property comes with independent Terrace. The area is centrally located and close to ring road which allows easy acess to all other areas.Renowned Delhi Lawn Tennis Association is within 10 minutes walking distance.Green park market is walkable distance. read more Contact Owner View Phone No. Share Feedback Owner Hemant pajankar',
       'Safdarjung Enclave carpet area 1450 sqft status Ready to Move floor 3 out of 4 floors transaction Resale furnishing Semi-Furnished facing North - East overlooking Garden/Park, Main Road car parking 1 Covered, 1 Open bathroom 3 balcony 2 ownership Freehold Park facing builder floor apartment available for sale in safderjung enclave, 3 bedroom with attached bathroom, drawing dinning, modular kitchen. the property is on the top floor of a four storey building with terrace right, servant quarter, 1 car parking in stilt. read more Contact Agent View Phone No. Share Feedback Agent Delhi Homes Realty 1000+ Buyers Served',
       'Safdarjung Enclave super area 2200 sqft status Ready to Move floor 2 out of 4 floors transaction New Property furnishing Semi-Furnished facing South overlooking Main Road car parking 3 Covered, 2 Open bathroom 4 balcony 3 ownership Freehold Newly Constructed Property Wide Road 450 Yards 2nd floor brand new 4 bhk attached bathrooms with full lighted and ventilated house.Most Valuable DealSEE TO BELIEVE read more Contact Agent View Phone No. Share Feedback Crisil Bronze Agent Panchsheel Homes 500+ Buyers Served',
       'Paschim Vihar', 'Pushkar Enclave, Paschim Vihar',
       'Paschim Vihar Block B2', 'Paschimpuri, Paschim Vihar',
       'Paschim Vihar Block B4',
       'Paschim Vihar How Auctions work? The borrower has the physical possession of the Property. However the lender (Bank) can legally sell the Property. carpet area 780 sqft status Ready to Move floor Ground out of 3 floors transaction Resale furnishing Unfurnished facing West bathroom 2 balcony 1 ownership Freehold Contact Now Enquire Now Auction By Bank',
       'DDA Lig Flats, Paschim Vihar carpet area 45 sqyrd status Ready to Move floor 4 out of 4 floors transaction Resale furnishing Semi-Furnished facing East overlooking Garden/Park, Main Road society DDA Lig Flats bathroom 1 balcony 1 ownership Freehold East Facing Property Expected price for the Flat is kept at 45 Lac. This is a 1 bedroom apartment present in DDA Lig Flats, Paschim Vihar. It measures an area of 45 Sq-m. It is on 4 floor out of 4 floors in the tower and is also well ventilated. The Flat has 1 washroom and also has 1 spacious balcony. read more Contact Owner View Phone No. Share Feedback Owner Anil',
       'Archana Apartment, Paschim Vihar',
       'Guru Harikishan Nagar, Paschim Vihar',
       'Mianwali Nagar, Paschim Vihar',
       'Navbharat Apartment, Paschim Vihar Block B1',
       'Paschim Vihar Block A2', 'LIC Colony, Paschim Vihar',
       'DDA Lig Flats, Paschim Vihar',

In [22]:
dummies4 = pd.get_dummies(df8.Locality)
dummies4.head()

,"APL Builder Floor, Greater Kailash 1","Aashirwaad Chowk, Dwarka","Abhimanyu Apartments, Vasundhara Enclave","Abul Fazal Enclave Part 1, Okhla","Abul Fazal Enclave Part-II, Okhla","Adarsh Homes, Dwarka Mor","Ahinsha Vatika, Ram Nagar, Shahdara",Alaknanda,"Amar Colony, Lajpat Nagar","Andheria Mor, Mehrauli",...,"Vijay Enclave, Mahavir Enclave","Vijay Vihar, Rohini","Vikram Vihar, Lajpat Nagar","Vinoba Puri, Lajpat Nagar","Virat Residency, Dwarka Mor","Vishwas Nagar, Shahdara","Yamuna Apartment, Alaknanda","Yamuna Vihar, Shahdara","Zakir Nagar, New Friends Colony","mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar"
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
df9 = pd.concat([df8,dummies4],axis='columns')
df9.head()

,Area,BHK,Bathroom,Locality,Parking,Price,Furnished,Semi-Furnished,Unfurnished,New_Property,...,"Vijay Enclave, Mahavir Enclave","Vijay Vihar, Rohini","Vikram Vihar, Lajpat Nagar","Vinoba Puri, Lajpat Nagar","Virat Residency, Dwarka Mor","Vishwas Nagar, Shahdara","Yamuna Apartment, Alaknanda","Yamuna Vihar, Shahdara","Zakir Nagar, New Friends Colony","mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar"
0,800.0,3,2.0,Rohini Sector 25,1.0,6500000,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,750.0,2,2.0,"J R Designers Floors, Rohini Sector 24",1.0,5000000,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,950.0,2,2.0,"Citizen Apartment, Rohini Sector 13",1.0,15500000,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,600.0,2,2.0,Rohini Sector 24,1.0,4200000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,650.0,2,2.0,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [26]:
df_final = df9.drop('Locality',axis='columns')
df_final

,Area,BHK,Bathroom,Parking,Price,Furnished,Semi-Furnished,Unfurnished,New_Property,Resale,...,"Vijay Enclave, Mahavir Enclave","Vijay Vihar, Rohini","Vikram Vihar, Lajpat Nagar","Vinoba Puri, Lajpat Nagar","Virat Residency, Dwarka Mor","Vishwas Nagar, Shahdara","Yamuna Apartment, Alaknanda","Yamuna Vihar, Shahdara","Zakir Nagar, New Friends Colony","mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar"
0,800.0,3,2.0,1.0,6500000,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,750.0,2,2.0,1.0,5000000,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,950.0,2,2.0,1.0,15500000,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,600.0,2,2.0,1.0,4200000,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,650.0,2,2.0,1.0,6200000,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,3.0,55000000,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1255,1050.0,3,2.0,3.0,12500000,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1256,875.0,3,3.0,3.0,17500000,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1257,990.0,2,2.0,1.0,11500000,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1258,11050.0,3,3.0,1.0,18500000,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
x = df_final.drop('Price',axis='columns')
y = df_final.Price

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3)

In [36]:
models = {
    "                     Linear Regression": LinearRegression(),
    " Linear Regression (L2 Regularization)": Ridge(),
    " Linear Regression (L1 Regularization)": Lasso(),
    "                   K-Nearest Neighbors": KNeighborsRegressor(),
    "                        Neural Network": MLPRegressor(),
    "Support Vector Machine (Linear Kernel)": LinearSVR(),
    "   Support Vector Machine (RBF Kernel)": SVR(),
    "                         Decision Tree": DecisionTreeRegressor(),
    "                         Random Forest": RandomForestRegressor(),
    "                     Gradient Boosting": GradientBoostingRegressor()
}


for name,model in models.items():
    model.fit(x_train,y_train)
    print(name + "model trained..")

                     Linear Regressionmodel trained..
 Linear Regression (L2 Regularization)model trained..
 Linear Regression (L1 Regularization)model trained..
                   K-Nearest Neighborsmodel trained..
                        Neural Networkmodel trained..
Support Vector Machine (Linear Kernel)model trained..
   Support Vector Machine (RBF Kernel)model trained..
                         Decision Treemodel trained..
                         Random Forestmodel trained..
                     Gradient Boostingmodel trained..

In [37]:
for name,model in models.items():
     print(name + " R^2 Score: {:.5f}".format(model.score(x_test, y_test)))

                     Linear Regression R^2 Score: -6285322140938.29688
 Linear Regression (L2 Regularization) R^2 Score: 0.62176
 Linear Regression (L1 Regularization) R^2 Score: 0.60293
                   K-Nearest Neighbors R^2 Score: 0.55821
                        Neural Network R^2 Score: -0.67629
Support Vector Machine (Linear Kernel) R^2 Score: 0.09519
   Support Vector Machine (RBF Kernel) R^2 Score: -0.04162
                         Decision Tree R^2 Score: 0.68010
                         Random Forest R^2 Score: 0.83234
                     Gradient Boosting R^2 Score: 0.83479

In [39]:
best_model = GradientBoostingRegressor()

In [40]:
best_model.fit(x_train,y_train)

GradientBoostingRegressor()

In [60]:
best_model.score(x_test,y_test)

0.8366482711711581

In [61]:
import pickle
with open('delhi_houseprice_model.pickle','wb') as f:
    pickle.dump(best_model,f)

In [62]:
import json
columns = {
    'data_column' : [col.lower() for col in x.columns]
}

with open('columns.json','w') as f:
    f.write(json.dumps(columns))